### ISSUE TITLE
Feature request: Add a `pre-gap` input to allow for gap to be run within a different tool

### ISSUE THREAD

**Issue by Joseph-Edwards** [gap-actions/run-pkg-tests#30]
When checking for memory leaks in `test_file.g`, I run `valgrind --trace-children=yes --leak-check=full gap test_file.g`. It'd be nice to be able to pass a command that should be prepended to the variable `$GAP`. In this example, this would be invoked with something like
```yml
...
  - name:
    uses:  gap-actions/run-pkg-tests@v2
    with:
      GAP_TESTFILE: "test_file.g"
      pre-gap: valgrind --trace-children=yes --leak-check=full 
```
